### PR TITLE
Adjust test2 to pass

### PR DESCRIPTION
**Pull request by keszybz**
I was running enjarify.runtests from the v1.0.3 checkout, and test2 failed with one difference (see patch). I'm assuming the test is wrong, but if not — please treat this as an issue report.

### CODE REVIEW

**Comment by Storyyeller** [comment]
The issue is that the behavior of Java itself changed. The current test passes on older versions of Java, but fails on newer versions. I'm not really sure what to do about it.

**Comment by keszybz** [comment]
Ah, good to know. I have no idea.

You *could* update the test case based on `java` version, e.g. by tweaking the "expected" text in memory, but I don't know if this is worth the hassle.

Anyway, I'm working on a Fedora package [https://bugzilla.redhat.com/show_bug.cgi?id=1415331], as a dependency of diffoscope. We don't really care about anything older than java 1.8, so the patch is good enough for us.

**Comment by Storyyeller** [comment]
By the way, you may want to consider using hashtests instead as a temporary workaround.

Basically, there are two different types of tests
runtests.py will translate the test files, execute them on the JVM, and check whether the output is expected
hashtest.py will translate the test files (under every possible combination of options) and output a hash of the output

If you make changes to Enjarify which are not intended to affect the output of the program (refactoring, optimization, etc.) you can easily check for regressions by running hashtests and comparing it to a known good output hash. 
runtests is useful when you intentionally change the behavior of Enjarify and want to make sure that the output is still sensible. However, since it is tied to the JVM, it is vulnerable to all the issues you might expect, such as in this case, a change in the JVM behavior since the tests were first written.

Also note that neither test checks the "UI" logic, such as command line argument parsing, handling of missing files, etc. I'm not sure if it's worth adding this kind of test. It would probably have to be done as a shell script in order to test the command line interface with full fidelity.

Any suggestions to improve testing are welcome.


P.S. I noticed that this is for Diffoscope, and while it should work for diffing dex files, you are likely better off using Smali, which would produce less noisy diffs, since it avoids the extra optimization and translation step. Then again, it depends on the exact behavior you want.

**Comment by keszybz** [comment]
Thanks, I'll forward those recommendations to the debian guys. I'm not really involved in diffoscope (or enjarify development), I'm just trying to package it and all deps for Fedora.

**Pull request merged**
