### PR TITLE
fix enjarify.main not foundError on macos

### PR DESCRIPTION
**Pull request by jbg168**
on mac os,not in enjarify.sh dir run enjarify command, I got Python ImportError: No module named 'enjarify.man' Error, echo $PYTHONPATH got '.'

### CODE REVIEW

**Comment by zyv** [comment]
Confirmed broken and fixed through this PR here on macOS 10.14.

**Comment by Storyyeller** [comment]
I looked into this, but it looks like it conflicts with https://github.com/Storyyeller/enjarify/pull/6, since `readlink -f` is not supported on Macs. What do you think we should do?

**Comment by zyv** [comment]
@Storyyeller, you are right, I would do something like this to keep compatibility with Linux:

```bash
	if [[ "$OSTYPE" == "darwin"* ]]; then
		READLINK="readlink"
	else
		READLINK="readlink -f"
	fi

	export PYTHONPATH=$(dirname "$($READLINK "${BASH_SOURCE[0]}")")
```

will this do, or shall I submit a PR? I can't edit this PR, since I'm not the original submitter :(

**Comment by Storyyeller** [comment]
Please confirm that it works on both linux and mac and then submit a PR

**Comment by zyv** [comment]
Done, tested on Debian and macOS 10.14.

**Pull request closed without merging**
